// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvYaPyRs5_9XQ70BacGPAeurrl8QtkjMA',
    appId: '1:840140708321:web:4858a226e275681b6b1aa0',
    messagingSenderId: '840140708321',
    projectId: 'event-management-27827',
    authDomain: 'event-management-27827.firebaseapp.com',
    storageBucket: 'event-management-27827.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRdhnkG8Ayb4UiJx4T0vkyGcN0uF_Ai1I',
    appId: '1:840140708321:android:b1f76031209ff9136b1aa0',
    messagingSenderId: '840140708321',
    projectId: 'event-management-27827',
    storageBucket: 'event-management-27827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV5XqW9GtI2Ct0MyiHVUitUsNeSjbmlpE',
    appId: '1:840140708321:ios:fec3818035c012dc6b1aa0',
    messagingSenderId: '840140708321',
    projectId: 'event-management-27827',
    storageBucket: 'event-management-27827.firebasestorage.app',
    iosBundleId: 'com.example.eventease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV5XqW9GtI2Ct0MyiHVUitUsNeSjbmlpE',
    appId: '1:840140708321:ios:fec3818035c012dc6b1aa0',
    messagingSenderId: '840140708321',
    projectId: 'event-management-27827',
    storageBucket: 'event-management-27827.firebasestorage.app',
    iosBundleId: 'com.example.eventease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvYaPyRs5_9XQ70BacGPAeurrl8QtkjMA',
    appId: '1:840140708321:web:7be9d8b2ec2a97846b1aa0',
    messagingSenderId: '840140708321',
    projectId: 'event-management-27827',
    authDomain: 'event-management-27827.firebaseapp.com',
    storageBucket: 'event-management-27827.firebasestorage.app',
  );
}
